myapp:
  website:
    # 网站 URL
    url: http://localhost:8080/my-blog/

  user:
    activate:
      # 用户注册网址链接
      url: http://localhost:8080/my-blog/user/account/activate/
      # 用户注册激活过期时间，单位小时
      expire-time: 24
    cancel:
      # 用户注销网址链接
      url: http://localhost:8080/my-blog/user/account/cancel/
      # 用户注销过期时间，单位小时
      expire-time: 24
      # 用来加解密“注销账号”参数的秘钥
      aes-key: IJCXtl2g9SExirSEs0kueA==

    password-retry:
      # 用户登录密码允许错误的最大次数
      max-count: 5
      # 用户密码错误超出次数后禁用的登录时长，单位分钟
      limit-minutes: 1

    # 用户忘记密码请求发送网址
    forget-password:
      url: http://localhost:8080/my-blog/user/password/forget/
      # 用户忘记密码请求过期时间，单位小时
      url-expire: 1
      # 用来加解密“忘记密码”参数的秘钥
      aes-key: xojDGXtVip8AuU4lj9KUJQ==

    # 用户头像基路径
    profile-picture-path: /img/user/profile-picture
    # 用户默认头像路径
    default-profile-picture-path: /img/user/profile-picture/default/default-man.jpeg

    # 用户默认简介
    default-description: 这个用户很懒，什么都没有说~

  request:
    flow-id:
      # 请求 flow id 写入模式
      write-mode: seconds
      # 请求 flow id 写入文件位置
      resource: data/app/requestFlowId.txt

  encryption:
    # 是否开启请求体/响应体加密模式
    enable: false
    # 服务器 RSA 秘钥过期时间间隔，单位毫秒。30 天
    rsa-key-expire: 2592000000
    # 服务器 RSA 秘钥的存储位置
    rsa-file-path: data/app/rsa.properties
    # 服务器 AES 秘钥过期时间间隔，单位毫秒。7 天
    aes-key-expire: 604800000
    # 服务器 AES 秘钥的存储位置
    aes-file-path: data/app/aes.properties
    # 不使用加解密功能的 url 前缀
    ignore-url-prefixes:
      - "/app/encryption"
      - "/user/account-activate"
      - "/password/forget"
      - "/blog/editor-md-img/upload"

  image:
    origin-filename-max-length: 150

  mail:
    # 是否启用发送邮件功能
    enable: false

  verification-code:
    # 是否启用验证码功能
    enable: true
    plain:
      # 普通验证码过期时间，单位分钟
      expireMinutes: 5